version: "3.8"

services:

  mariadb:
    image: mariadb
    volumes:
      - "./database_scripts:/docker-entrypoint-initdb.d/"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
    container_name: mariadb
    hostname: mariadb
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build:
      context: ./backend
    restart: unless-stopped
    ports: 
     - 8080:80
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - mariadb
