version: "3.8"

services:

  mariadb:
    image: mariadb
    volumes:
      - "./database_scripts:/docker-entrypoint-initdb.d/"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADBPWD}
    container_name: mariadb
    hostname: mariadb
    ports:
      - "${MARIADB}:3306"

  backend:
    container_name: backend
    build:
      context: ./backend
    restart: unless-stopped
    ports: 
     - '${BACKEND}:80'
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - mariadb
    environment:
      - NODE_ENV=development

  composer:
    restart: 'no'
    image: composer:latest
    command: install
    volumes:
      - ./backend:/app
    depends_on:
      - backend

  frontend:
      container_name: frontend
      build:
          context: ./frontend
          dockerfile: Dockerfile
      volumes:
          - './frontend:/app'
          - '/app/node_modules'
      ports:
          - '${FRONTEND}:3000'
      environment:
          - NODE_ENV=development
      depends_on:
          - backend
